### ISSUE TITLE
there is no documentation about using with "javadoc = 0" parameter

### ISSUE THREAD

**Issue by shredder2003** [IzzySoft/HyperSQL#1]
I tried any kind of declarations:

/*\* Consolidate constants and environtment variables, exceptions etc.
- Some variables can be initialized by profiles.
  _/
  /_! Передо мной объект который я описываю. _/
  /// Передо мной объект который я описываю 2.
  CREATE OR REPLACE PACKAGE BODY APPS.XXT_ENV
  /_!< Передо мной объект который я описываю. _/
  is
  /_!< Передо мной объект который я описываю 3. */

![1](https://cloud.githubusercontent.com/assets/218283/9257415/1a8e727c-41fe-11e5-9d78-9ab63a6df094.PNG)

but I get same result - "Details" is empty in file PackageIndex.html:

Index Of All Packages
 Package _____ Details _____ Usage
apps.xxt_env ___________no use found

![2](https://cloud.githubusercontent.com/assets/218283/9257408/0de19ed2-41fe-11e5-835c-08a634b61062.PNG)

How to fill Details field in this case?

**Comment by IzzySoft** [comment]
Sorry that I cannot be of much help (as you can see, it's several years ago that I've last worked on the code – I've put it here to Github on request of someone looking into participating in the project, but unfortunately nothing happened since). Still wanted to give you at least a little feedback so you don't get the feeling of being completely abandoned.

You probably have already checked with the [documentation on the original project site](http://projects.izzysoft.de/trac/hypersql/wiki/Configuration#Configuration) I guess. And I'm still not sure if I understand your issue correctly: what did you expect to see? I don't know all your code, but from what you put into the issue, the screenshot looks correct to me. `javadoc=0` turns off the JavaDoc output, so it wouldn't show.
